//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;


namespace <%= LanguageName %>.FiniteStateMachines
{
    
    
    /// <summary>
    /// The public interface for Transition
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(Transition))]
    [XmlDefaultImplementationTypeAttribute(typeof(Transition))]
    [ModelRepresentationClassAttribute("about:fsm#//Transition")]
    public partial interface ITransition : IModelElement
    {
        
        /// <summary>
        /// The trigger property
        /// </summary>
        [DisplayNameAttribute("trigger")]
        [CategoryAttribute("Transition")]
        [XmlElementNameAttribute("trigger")]
        [XmlAttributeAttribute(true)]
        string Trigger
        {
            get;
            set;
        }
        
        /// <summary>
        /// The source property
        /// </summary>
        [BrowsableAttribute(false)]
        [XmlElementNameAttribute("source")]
        [XmlAttributeAttribute(true)]
        [DesignerSerializationVisibilityAttribute(DesignerSerializationVisibility.Hidden)]
        [XmlOppositeAttribute("outgoing")]
        IState Source
        {
            get;
            set;
        }
        
        /// <summary>
        /// The target property
        /// </summary>
        [DisplayNameAttribute("target")]
        [CategoryAttribute("Transition")]
        [XmlElementNameAttribute("target")]
        [XmlAttributeAttribute(true)]
        [XmlOppositeAttribute("incoming")]
        IState Target
        {
            get;
            set;
        }
    }
}
